### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jorisslob** [Siriah/codegarden#2]
When I run npm install I get the following error:

```
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> node-sass@3.7.0 install /home/jorisslob/Repositories/codegarden/node_modules/node-sass
> node scripts/install.js

sh: 1: node: not found
phaser-demo@0.1.0 /home/jorisslob/Repositories/codegarden
├── bower@1.7.9 
├─┬ browser-sync@2.12.10 
│ ├─┬ browser-sync-client@2.4.2 
│ │ ├── etag@1.7.0 
│ │ └── fresh@0.3.0 
│ ├─┬ browser-sync-ui@0.5.19 
│ │ ├── async-each-series@0.1.1 
│ │ ├── connect-history-api-fallback@1.2.0 
│ │ ├─┬ stream-throttle@0.1.3 
│ │ │ ├── commander@2.9.0 
│ │ │ └── limiter@1.1.0 
│ │ └─┬ weinre@2.0.0-pre-I0Z7U9OV 
│ │   ├─┬ express@2.5.11 
│ │   │ ├─┬ connect@1.9.2 
│ │   │ │ └── formidable@1.0.17 
│ │   │ ├── mime@1.2.4 
│ │   │ ├── mkdirp@0.3.0 
│ │   │ └── qs@0.4.2 
│ │   ├─┬ nopt@3.0.6 
│ │   │ └── abbrev@1.0.7 
│ │   └── underscore@1.7.0 
│ ├── bs-recipes@1.2.2 
│ ├─┬ chokidar@1.5.1 
│ │ ├── anymatch@1.3.0 
│ │ ├── async-each@1.0.0 
│ │ ├── glob-parent@2.0.0 
│ │ ├── inherits@2.0.1 
│ │ ├─┬ is-binary-path@1.0.1 
│ │ │ └── binary-extensions@1.4.1 
│ │ ├── is-glob@2.0.1 
│ │ ├── path-is-absolute@1.0.0 
│ │ └─┬ readdirp@2.0.0 
│ │   └── minimatch@2.0.10 
│ ├─┬ connect@3.4.1 
│ │ ├─┬ debug@2.2.0 
│ │ │ └── ms@0.7.1 
│ │ ├─┬ finalhandler@0.4.1 
│ │ │ ├─┬ on-finished@2.3.0 
│ │ │ │ └── ee-first@1.1.1 
│ │ │ └── unpipe@1.0.0 
│ │ ├── parseurl@1.3.1 
│ │ └── utils-merge@1.0.0 
│ ├── dev-ip@1.0.1 
│ ├─┬ easy-extender@2.3.2 
│ │ └── lodash@3.10.1 
│ ├─┬ eazy-logger@2.1.3 
│ │ ├─┬ lodash.clonedeep@4.3.1 
│ │ │ └── lodash._baseclone@4.5.7 
│ │ ├── opt-merger@1.1.1 
│ │ └─┬ tfunk@3.0.2 
│ │   └── object-path@0.9.2 
│ ├── emitter-steward@1.0.0 
│ ├─┬ fs-extra@0.26.7 
│ │ ├── graceful-fs@4.1.4 
│ │ ├── jsonfile@2.3.1 
│ │ └── klaw@1.2.0 
│ ├─┬ http-proxy@1.13.3 
│ │ ├── eventemitter3@1.2.0 
│ │ └── requires-port@1.0.0 
│ ├── immutable@3.8.1 
│ ├─┬ localtunnel@1.8.1 
│ │ ├── openurl@1.1.0 
│ │ ├─┬ request@2.65.0 
│ │ │ ├── aws-sign2@0.6.0 
│ │ │ ├─┬ bl@1.0.3 
│ │ │ │ └── readable-stream@2.0.6 
│ │ │ ├── caseless@0.11.0 
│ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ └── delayed-stream@1.0.0 
│ │ │ ├── forever-agent@0.6.1 
│ │ │ ├── form-data@1.0.0-rc4 
│ │ │ ├─┬ har-validator@2.0.6 
│ │ │ │ └─┬ is-my-json-valid@2.13.1 
│ │ │ │   ├── generate-function@2.0.0 
│ │ │ │   ├─┬ generate-object-property@1.2.0 
│ │ │ │   │ └── is-property@1.0.2 
│ │ │ │   └── jsonpointer@2.0.0 
│ │ │ ├─┬ hawk@3.1.3 
│ │ │ │ ├── boom@2.10.1 
│ │ │ │ ├── cryptiles@2.0.5 
│ │ │ │ ├── hoek@2.16.3 
│ │ │ │ └── sntp@1.0.9 
│ │ │ ├─┬ http-signature@0.11.0 
│ │ │ │ ├── asn1@0.1.11 
│ │ │ │ ├── assert-plus@0.1.5 
│ │ │ │ └── ctype@0.5.3 
│ │ │ ├── isstream@0.1.2 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├── oauth-sign@0.8.2 
│ │ │ ├── qs@5.2.0 
│ │ │ ├── stringstream@0.0.5 
│ │ │ ├── tough-cookie@2.2.2 
│ │ │ └── tunnel-agent@0.4.3 
│ │ └─┬ yargs@3.29.0 
│ │   └── camelcase@1.2.1 
│ ├─┬ micromatch@2.3.7 
│ │ ├─┬ arr-diff@2.0.0 
│ │ │ └── arr-flatten@1.0.1 
│ │ ├── array-unique@0.2.1 
│ │ ├─┬ braces@1.8.5 
│ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │   ├── is-number@2.1.0 
│ │ │ │   ├── randomatic@1.1.5 
│ │ │ │   └── repeat-string@1.5.4 
│ │ │ ├── preserve@0.2.0 
│ │ │ └── repeat-element@1.1.2 
│ │ ├─┬ expand-brackets@0.1.5 
│ │ │ └── is-posix-bracket@0.1.1 
│ │ ├── extglob@0.3.2 
│ │ ├── filename-regex@2.0.0 
│ │ ├── is-extglob@1.0.0 
│ │ ├─┬ kind-of@3.0.3 
│ │ │ └── is-buffer@1.1.3 
│ │ ├── normalize-path@2.0.1 
│ │ ├─┬ object.omit@2.0.0 
│ │ │ ├─┬ for-own@0.1.4 
│ │ │ │ └── for-in@0.1.5 
│ │ │ └── is-extendable@0.1.1 
│ │ ├─┬ parse-glob@3.0.4 
│ │ │ ├── glob-base@0.3.0 
│ │ │ └── is-dotfile@1.0.2 
│ │ └─┬ regex-cache@0.4.3 
│ │   ├── is-equal-shallow@0.1.3 
│ │   └── is-primitive@2.0.0 
│ ├── opn@3.0.3 
│ ├─┬ portscanner@1.0.0 
│ │ └── async@0.1.15 
│ ├── qs@6.2.0 
│ ├─┬ resp-modifier@6.0.1 
│ │ └── minimatch@2.0.10 
│ ├─┬ serve-index@1.7.3 
│ │ ├─┬ accepts@1.2.13 
│ │ │ └── negotiator@0.5.3 
│ │ ├── batch@0.5.3 
│ │ ├── escape-html@1.0.3 
│ │ ├─┬ http-errors@1.3.1 
│ │ │ └── statuses@1.3.0 
│ │ └─┬ mime-types@2.1.11 
│ │   └── mime-db@1.23.0 
│ ├─┬ serve-static@1.10.2 
│ │ └─┬ send@0.13.1 
│ │   ├── depd@1.1.0 
│ │   ├── destroy@1.0.4 
│ │   ├── mime@1.3.4 
│ │   ├── range-parser@1.0.3 
│ │   └── statuses@1.2.1 
│ ├─┬ socket.io@1.4.6 
│ │ ├─┬ engine.io@1.6.9 
│ │ │ ├─┬ accepts@1.1.4 
│ │ │ │ ├─┬ mime-types@2.0.14 
│ │ │ │ │ └── mime-db@1.12.0 
│ │ │ │ └── negotiator@0.4.9 
│ │ │ ├── base64id@0.1.0 
│ │ │ ├─┬ engine.io-parser@1.2.4 
│ │ │ │ ├── after@0.8.1 
│ │ │ │ ├── arraybuffer.slice@0.0.6 
│ │ │ │ ├── base64-arraybuffer@0.1.2 
│ │ │ │ ├── blob@0.0.4 
│ │ │ │ ├─┬ has-binary@0.1.6 
│ │ │ │ │ └── isarray@0.0.1 
│ │ │ │ └── utf8@2.1.0 
│ │ │ └─┬ ws@1.0.1 
│ │ │   ├── options@0.0.6 
│ │ │   └── ultron@1.0.2 
│ │ ├─┬ has-binary@0.1.7 
│ │ │ └── isarray@0.0.1 
│ │ ├─┬ socket.io-adapter@0.4.0 
│ │ │ └─┬ socket.io-parser@2.2.2 
│ │ │   ├── debug@0.7.4 
│ │ │   ├── isarray@0.0.1 
│ │ │   └── json3@3.2.6 
│ │ ├─┬ socket.io-client@1.4.6 
│ │ │ ├── backo2@1.0.2 
│ │ │ ├── component-bind@1.0.0 
│ │ │ ├── component-emitter@1.2.0 
│ │ │ ├─┬ engine.io-client@1.6.9 
│ │ │ │ ├── component-inherit@0.0.3 
│ │ │ │ ├── has-cors@1.1.0 
│ │ │ │ ├── parsejson@0.0.1 
│ │ │ │ ├── parseqs@0.0.2 
│ │ │ │ ├── xmlhttprequest-ssl@1.5.1 
│ │ │ │ └── yeast@0.1.2 
│ │ │ ├── indexof@0.0.1 
│ │ │ ├── object-component@0.0.3 
│ │ │ ├─┬ parseuri@0.0.4 
│ │ │ │ └─┬ better-assert@1.0.2 
│ │ │ │   └── callsite@1.0.0 
│ │ │ └── to-array@0.1.4 
│ │ └─┬ socket.io-parser@2.2.6 
│ │   ├── benchmark@1.0.0 
│ │   ├── component-emitter@1.1.2 
│ │   ├── isarray@0.0.1 
│ │   └── json3@3.3.2 
│ ├── ua-parser-js@0.7.10 
│ └─┬ yargs@4.7.1 
│   ├── camelcase@3.0.0 
│   ├── decamelize@1.2.0 
│   ├─┬ lodash.assign@4.0.9 
│   │ ├── lodash.keys@4.0.7 
│   │ └── lodash.rest@4.0.3 
│   ├─┬ pkg-conf@1.1.3 
│   │ ├─┬ find-up@1.1.2 
│   │ │ └── path-exists@2.1.0 
│   │ ├─┬ load-json-file@1.1.0 
│   │ │ └─┬ parse-json@2.2.0 
│   │ │   └─┬ error-ex@1.3.0 
│   │ │     └── is-arrayish@0.2.1 
│   │ └── symbol@0.2.3 
│   ├─┬ read-pkg-up@1.0.1 
│   │ └─┬ read-pkg@1.1.0 
│   │   └── path-type@1.1.0 
│   ├── require-main-filename@1.0.1 
│   ├── set-blocking@1.0.0 
│   ├── window-size@0.2.0 
│   └─┬ yargs-parser@2.4.0 
│     └── camelcase@2.1.1 
├─┬ del@2.2.0 
│ ├─┬ globby@4.1.0 
│ │ ├── array-union@1.0.1 
│ │ ├── arrify@1.0.1 
│ │ └─┬ glob@6.0.4 
│ │   ├─┬ inflight@1.0.5 
│ │   │ └── wrappy@1.0.2 
│ │   ├── minimatch@3.0.0 
│ │   └── once@1.3.3 
│ ├── is-path-cwd@1.0.0 
│ ├─┬ is-path-in-cwd@1.0.0 
│ │ └─┬ is-path-inside@1.0.0 
│ │   └── path-is-inside@1.0.1 
│ ├── object-assign@4.1.0 
│ ├── pify@2.3.0 
│ ├─┬ pinkie-promise@2.0.1 
│ │ └── pinkie@2.0.4 
│ └─┬ rimraf@2.5.2 
│   └── glob@7.0.3 
├─┬ gulp@3.9.1 
│ ├── archy@1.0.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.0.0 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├── deprecated@0.0.1 
│ ├── interpret@1.0.1 
│ ├─┬ liftoff@2.2.1 
│ │ ├── extend@2.0.1 
│ │ ├─┬ findup-sync@0.3.0 
│ │ │ └── glob@5.0.15 
│ │ ├── flagged-respawn@0.3.2 
│ │ ├── rechoir@0.6.2 
│ │ └── resolve@1.1.7 
│ ├── minimist@1.2.0 
│ ├─┬ orchestrator@0.3.7 
│ │ ├── end-of-stream@0.1.5 
│ │ ├── sequencify@0.0.7 
│ │ └── stream-consume@0.1.0 
│ ├── pretty-hrtime@1.0.2 
│ ├── semver@4.3.6 
│ ├─┬ tildify@1.2.0 
│ │ └── os-homedir@1.0.1 
│ ├─┬ v8flags@2.0.11 
│ │ └── user-home@1.1.1 
│ └─┬ vinyl-fs@0.3.14 
│   ├── defaults@1.0.3 
│   ├─┬ glob-stream@3.1.18 
│   │ ├── glob@4.5.3 
│   │ ├─┬ glob2base@0.0.12 
│   │ │ └── find-index@0.1.1 
│   │ ├── minimatch@2.0.10 
│   │ ├── ordered-read-streams@0.1.0 
│   │ ├─┬ through2@0.6.5 
│   │ │ └─┬ readable-stream@1.0.34 
│   │ │   └── isarray@0.0.1 
│   │ └── unique-stream@1.0.0 
│   ├─┬ glob-watcher@0.0.6 
│   │ └─┬ gaze@0.5.2 
│   │   └─┬ globule@0.1.0 
│   │     ├─┬ glob@3.1.21 
│   │     │ ├── graceful-fs@1.2.3 
│   │     │ └── inherits@1.0.2 
│   │     ├── lodash@1.0.2 
│   │     └── minimatch@0.2.14 
│   ├── graceful-fs@3.0.8 
│   ├─┬ mkdirp@0.5.1 
│   │ └── minimist@0.0.8 
│   ├─┬ strip-bom@1.0.0 
│   │ ├── first-chunk-stream@1.0.0 
│   │ └── is-utf8@0.2.1 
│   ├─┬ through2@0.6.5 
│   │ └─┬ readable-stream@1.0.34 
│   │   └── isarray@0.0.1 
│   └─┬ vinyl@0.4.6 
│     └── clone@0.2.0 
├─┬ gulp-autoprefixer@3.1.0 
│ ├─┬ autoprefixer@6.3.6 
│ │ ├── browserslist@1.3.2 
│ │ ├── caniuse-db@1.0.30000471 
│ │ ├── normalize-range@0.1.2 
│ │ ├── num2fraction@1.2.2 
│ │ └── postcss-value-parser@3.3.0 
│ ├─┬ postcss@5.0.21 
│ │ ├── js-base64@2.1.9 
│ │ └─┬ supports-color@3.1.2 
│ │   └── has-flag@1.0.0 
│ ├─┬ through2@2.0.1 
│ │ ├── readable-stream@2.0.6 
│ │ └── xtend@4.0.1 
│ └── vinyl-sourcemaps-apply@0.2.1 
├── gulp-changed@1.3.0 
├─┬ gulp-clean@0.3.2 
│ ├─┬ gulp-util@2.2.20 
│ │ ├─┬ chalk@0.5.1 
│ │ │ ├── ansi-styles@1.1.0 
│ │ │ ├─┬ has-ansi@0.1.0 
│ │ │ │ └── ansi-regex@0.2.1 
│ │ │ ├── strip-ansi@0.3.0 
│ │ │ └── supports-color@0.2.0 
│ │ ├── lodash._reinterpolate@2.4.1 
│ │ ├─┬ lodash.template@2.4.1 
│ │ │ ├── lodash._escapestringchar@2.4.1 
│ │ │ ├─┬ lodash.defaults@2.4.1 
│ │ │ │ ├── lodash._objecttypes@2.4.1 
│ │ │ │ └── lodash.keys@2.4.1 
│ │ │ ├─┬ lodash.escape@2.4.1 
│ │ │ │ ├─┬ lodash._escapehtmlchar@2.4.1 
│ │ │ │ │ └── lodash._htmlescapes@2.4.1 
│ │ │ │ └─┬ lodash._reunescapedhtml@2.4.1 
│ │ │ │   └── lodash.keys@2.4.1 
│ │ │ ├─┬ lodash.keys@2.4.1 
│ │ │ │ ├── lodash._isnative@2.4.1 
│ │ │ │ ├── lodash._shimkeys@2.4.1 
│ │ │ │ └── lodash.isobject@2.4.1 
│ │ │ ├── lodash.templatesettings@2.4.1 
│ │ │ └─┬ lodash.values@2.4.1 
│ │ │   └── lodash.keys@2.4.1 
│ │ ├── minimist@0.2.0 
│ │ ├─┬ through2@0.5.1 
│ │ │ └── xtend@3.0.0 
│ │ └── vinyl@0.2.3 
│ └─┬ through2@0.4.2 
│   ├─┬ readable-stream@1.0.34 
│   │ └── isarray@0.0.1 
│   └─┬ xtend@2.1.2 
│     └── object-keys@0.4.0 
├─┬ gulp-concat@2.6.0 
│ ├── concat-with-sourcemaps@1.0.4 
│ └─┬ through2@0.6.5 
│   └─┬ readable-stream@1.0.34 
│     └── isarray@0.0.1 
├─┬ gulp-file-include@0.13.7 
│ ├── balanced-match@0.2.1 
│ ├─┬ concat-stream@1.5.1 
│ │ ├── readable-stream@2.0.6 
│ │ └── typedarray@0.0.6 
│ ├── extend@3.0.0 
│ └── flatnest@1.0.0 
├─┬ gulp-minify-css@1.2.4 
│ ├─┬ clean-css@3.4.14 
│ │ ├─┬ commander@2.8.1 
│ │ │ └── graceful-readlink@1.0.1 
│ │ └─┬ source-map@0.4.4 
│ │   └── amdefine@1.0.0 
│ ├─┬ readable-stream@2.1.4 
│ │ ├── buffer-shims@1.0.0 
│ │ ├── core-util-is@1.0.2 
│ │ ├── isarray@1.0.0 
│ │ ├── process-nextick-args@1.0.7 
│ │ ├── string_decoder@0.10.31 
│ │ └── util-deprecate@1.0.2 
│ └─┬ vinyl-bufferstream@1.0.1 
│   └─┬ bufferstreams@1.0.1 
│     └─┬ readable-stream@1.1.14 
│       └── isarray@0.0.1 
├─┬ gulp-minify-html@1.0.6 
│ ├─┬ minimize@1.8.1 
│ │ ├── argh@0.1.4 
│ │ ├── async@1.5.2 
│ │ ├─┬ cli-color@1.1.0 
│ │ │ ├── d@0.1.1 
│ │ │ ├─┬ es5-ext@0.10.11 
│ │ │ │ └── es6-symbol@3.0.2 
│ │ │ ├── es6-iterator@2.0.0 
│ │ │ ├─┬ memoizee@0.3.10 
│ │ │ │ ├─┬ es6-weak-map@0.1.4 
│ │ │ │ │ ├── es6-iterator@0.1.3 
│ │ │ │ │ └── es6-symbol@2.0.1 
│ │ │ │ ├── event-emitter@0.3.4 
│ │ │ │ ├── lru-queue@0.1.0 
│ │ │ │ └── next-tick@0.2.2 
│ │ │ └── timers-ext@0.1.0 
│ │ ├─┬ diagnostics@1.0.1 
│ │ │ ├─┬ colorspace@1.0.1 
│ │ │ │ ├─┬ color@0.8.0 
│ │ │ │ │ ├── color-convert@0.5.3 
│ │ │ │ │ └─┬ color-string@0.3.0 
│ │ │ │ │   └── color-name@1.1.1 
│ │ │ │ └── text-hex@0.0.0 
│ │ │ ├─┬ enabled@1.0.2 
│ │ │ │ └── env-variable@0.0.3 
│ │ │ └─┬ kuler@0.0.0 
│ │ │   └── colornames@0.0.2 
│ │ ├── emits@3.0.0 
│ │ ├─┬ htmlparser2@3.9.0 
│ │ │ ├── domelementtype@1.3.0 
│ │ │ ├── domhandler@2.3.0 
│ │ │ ├─┬ domutils@1.5.1 
│ │ │ │ └─┬ dom-serializer@0.1.0 
│ │ │ │   └── domelementtype@1.1.3 
│ │ │ └── entities@1.1.1 
│ │ └── node-uuid@1.4.7 
│ └─┬ through2@0.6.5 
│   └─┬ readable-stream@1.0.34 
│     └── isarray@0.0.1 
├─┬ gulp-size@2.1.0 
│ ├─┬ gzip-size@3.0.0 
│ │ └── duplexer@0.1.1 
│ ├─┬ pretty-bytes@3.0.1 
│ │ └── number-is-nan@1.0.0 
│ └── stream-counter@1.0.0 
├─┬ gulp-strip-debug@1.1.0 
│ └─┬ strip-debug@1.1.1 
│   ├─┬ rocambole@0.5.1 
│   │ └── esprima@2.7.2 
│   ├─┬ rocambole-strip-alert@1.0.0 
│   │ └─┬ rocambole-node-update@1.0.1 
│   │   └── rocambole-token@1.2.1 
│   ├── rocambole-strip-console@1.0.0 
│   └─┬ rocambole-strip-debugger@1.0.0 
│     └── rocambole-node-remove@1.0.0 
├─┬ gulp-tslint@3.6.0 
│ ├── map-stream@0.1.0 
│ ├─┬ rcloader@0.1.4 
│ │ └─┬ rcfinder@0.1.9 
│ │   └── lodash.clonedeep@4.3.2 
│ ├── through@2.3.8 
│ └─┬ tslint@2.5.1 
│   ├─┬ findup-sync@0.2.1 
│   │ └─┬ glob@4.3.5 
│   │   └── minimatch@2.0.10 
│   ├─┬ optimist@0.6.1 
│   │ ├── minimist@0.0.10 
│   │ └── wordwrap@0.0.3 
│   └── underscore.string@3.1.1 
├─┬ gulp-typescript@2.13.5 
│ ├── source-map@0.5.6 
│ ├── typescript@1.8.10 
│ └─┬ vinyl-fs@2.4.3 
│   ├─┬ duplexify@3.4.3 
│   │ └── end-of-stream@1.0.0 
│   ├─┬ glob-stream@5.3.2 
│   │ ├── glob@5.0.15 
│   │ ├─┬ ordered-read-streams@0.3.0 
│   │ │ └── is-stream@1.1.0 
│   │ ├─┬ through2@0.6.5 
│   │ │ └─┬ readable-stream@1.0.34 
│   │ │   └── isarray@0.0.1 
│   │ ├─┬ to-absolute-glob@0.1.1 
│   │ │ └── extend-shallow@2.0.1 
│   │ └─┬ unique-stream@2.2.1 
│   │   └─┬ json-stable-stringify@1.0.1 
│   │     └── jsonify@0.0.0 
│   ├─┬ gulp-sourcemaps@1.6.0 
│   │ ├── convert-source-map@1.2.0 
│   │ └── vinyl@1.1.1 
│   ├── is-valid-glob@0.3.0 
│   ├── lazystream@1.0.0 
│   ├─┬ lodash.isequal@4.2.0 
│   │ └── lodash._root@3.0.1 
│   ├── merge-stream@1.0.0 
│   ├─┬ mkdirp@0.5.1 
│   │ └── minimist@0.0.8 
│   ├── strip-bom@2.0.0 
│   ├── strip-bom-stream@1.0.0 
│   ├── through2-filter@2.0.0 
│   ├── vali-date@1.0.0 
│   └── vinyl@1.1.1 
├─┬ gulp-uglify@1.5.3 
│ ├── deap@1.0.0 
│ ├─┬ fancy-log@1.2.0 
│ │ └── time-stamp@1.0.1 
│ ├── isobject@2.1.0 
│ ├─┬ uglify-js@2.6.2 
│ │ ├── async@0.2.10 
│ │ ├── uglify-to-browserify@1.0.2 
│ │ └─┬ yargs@3.10.0 
│ │   ├─┬ cliui@2.1.0 
│ │   │ ├─┬ center-align@0.1.3 
│ │   │ │ ├─┬ align-text@0.1.4 
│ │   │ │ │ └── longest@1.0.1 
│ │   │ │ └── lazy-cache@1.0.4 
│ │   │ ├── right-align@0.1.3 
│ │   │ └── wordwrap@0.0.2 
│ │   └── window-size@0.1.0 
│ └── uglify-save-license@0.4.1 
├─┬ gulp-util@3.0.7 
│ ├── array-differ@1.0.0 
│ ├── array-uniq@1.0.2 
│ ├── beeper@1.1.0 
│ ├─┬ dateformat@1.0.12 
│ │ ├── get-stdin@4.0.1 
│ │ └─┬ meow@3.7.0 
│ │   ├─┬ camelcase-keys@2.1.0 
│ │   │ └── camelcase@2.1.1 
│ │   ├─┬ loud-rejection@1.3.0 
│ │   │ ├── array-find-index@1.0.1 
│ │   │ └── signal-exit@2.1.2 
│ │   ├── map-obj@1.0.1 
│ │   ├─┬ normalize-package-data@2.3.5 
│ │   │ ├── hosted-git-info@2.1.5 
│ │   │ ├─┬ is-builtin-module@1.0.0 
│ │   │ │ └── builtin-modules@1.1.1 
│ │   │ ├── semver@5.1.0 
│ │   │ └─┬ validate-npm-package-license@3.0.1 
│ │   │   ├─┬ spdx-correct@1.0.2 
│ │   │   │ └── spdx-license-ids@1.2.1 
│ │   │   └─┬ spdx-expression-parse@1.0.2 
│ │   │     └── spdx-exceptions@1.0.4 
│ │   ├─┬ redent@1.0.0 
│ │   │ ├─┬ indent-string@2.1.0 
│ │   │ │ └─┬ repeating@2.0.1 
│ │   │ │   └── is-finite@1.0.1 
│ │   │ └── strip-indent@1.0.1 
│ │   └── trim-newlines@1.0.0 
│ ├─┬ gulplog@1.0.0 
│ │ └── glogg@1.0.0 
│ ├─┬ has-gulplog@0.1.0 
│ │ └── sparkles@1.0.0 
│ ├── lodash._reescape@3.0.0 
│ ├── lodash._reevaluate@3.0.0 
│ ├── lodash._reinterpolate@3.0.0 
│ ├─┬ lodash.template@3.6.2 
│ │ ├── lodash._basecopy@3.0.1 
│ │ ├── lodash._basetostring@3.0.1 
│ │ ├── lodash._basevalues@3.0.0 
│ │ ├── lodash._isiterateecall@3.0.9 
│ │ ├── lodash.escape@3.2.0 
│ │ ├─┬ lodash.keys@3.1.2 
│ │ │ ├── lodash._getnative@3.9.1 
│ │ │ ├── lodash.isarguments@3.0.8 
│ │ │ └── lodash.isarray@3.0.4 
│ │ ├── lodash.restparam@3.6.1 
│ │ └── lodash.templatesettings@3.1.1 
│ ├─┬ multipipe@0.1.2 
│ │ └─┬ duplexer2@0.0.2 
│ │   └─┬ readable-stream@1.1.14 
│ │     └── isarray@0.0.1 
│ ├── object-assign@3.0.0 
│ ├── replace-ext@0.0.1 
│ └─┬ vinyl@0.5.3 
│   ├── clone@1.0.2 
│   └── clone-stats@0.0.1 
├─┬ jshint-stylish@2.2.0 
│ ├── log-symbols@1.0.2 
│ ├─┬ plur@2.1.2 
│ │ └── irregular-plurals@1.1.0 
│ ├── string-length@1.0.1 
│ └── text-table@0.2.0 
└── run-sequence@1.2.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN phaser-demo@0.1.0 No repository field.
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.7.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.7.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jorisslob/Repositories/codegarden/npm-debug.log
```

And in the npm-debug.log the following information:

```
8262 warn optional Skipping failed optional dependency /chokidar/fsevents:
8263 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
8264 warn phaser-demo@0.1.0 No repository field.
8265 verbose stack Error: node-sass@3.7.0 install: `node scripts/install.js`
8265 verbose stack spawn ENOENT
8265 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
8265 verbose stack     at emitTwo (events.js:87:13)
8265 verbose stack     at ChildProcess.emit (events.js:172:7)
8265 verbose stack     at maybeClose (internal/child_process.js:821:16)
8265 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
8266 verbose pkgid node-sass@3.7.0
8267 verbose cwd /home/jorisslob/Repositories/codegarden
8268 error Linux 4.4.0-22-generic
8269 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
8270 error node v4.2.6
8271 error npm  v3.5.2
8272 error file sh
8273 error code ELIFECYCLE
8274 error errno ENOENT
8275 error syscall spawn
8276 error node-sass@3.7.0 install: `node scripts/install.js`
8276 error spawn ENOENT
8277 error Failed at the node-sass@3.7.0 install script 'node scripts/install.js'.
8277 error Make sure you have the latest version of node.js and npm installed.
8277 error If you do, this is most likely a problem with the node-sass package,
8277 error not with npm itself.
8277 error Tell the author that this fails on your system:
8277 error     node scripts/install.js
8277 error You can get information on how to open an issue for this project with:
8277 error     npm bugs node-sass
8277 error Or if that isn't available, you can get their info via:
8277 error     npm owner ls node-sass
8277 error There is likely additional logging output above.
8278 verbose exit [ 1, true ]
```

This is on Ubuntu 16.04
Package: nodejs
Version: 4.2.6~dfsg-1ubuntu4

Package: npm
Version: 3.5.2-0ubuntu4

**Comment by Siriah** [comment]
The error is sh: 1: node: not found so it sounds like this problem: http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

Can you try the solutions provided in the Stackoverflow answers? So far, we have only tested the setup under Windows 7 and 10, it will be good to get this working on Ubuntu as well!

(BTW it 'works on my (personal Windows 7 laptop) machine' ;) )

**Comment by jorisslob** [comment]
@Siriah This indeed solves the problem. I will add the findings to the README.md and provide some Debian specific hints for installation.
