### ISSUE TITLE
Cannot run gulp commands

### ISSUE THREAD

**Issue by jorisslob** [Siriah/codegarden#3]
When I follow the README.md to get codegarden to work I get the following error:

```
/home/jslob/Repos/codegarden/gulpfile.js:37
gulp.task('browserSync', () => {
                          ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
```

Gulp version:
```
jslob@joris-asus-x73s ~/Repos/codegarden[master*]$ gulp -v
[21:56:28] CLI version 3.9.1
[21:56:28] Local version 3.9.1
```

**Comment by bogdanbikics** [comment]
It seems that it doesn't accept ECMAScript 6 fat arrows.
I think your node.js is old. I have 6.2.1.

**Comment by jorisslob** [comment]
I was running Ubuntu 14, with the latest nodejs available in the repository. I am now upgrading to Ubuntu 16.

**Comment by jorisslob** [comment]
Upgrading to Ubuntu 16 fixes it. The nodejs on Ubuntu 14 was hopelessly outdated.
