### ISSUE TITLE
Missing requirements for running the tests

### ISSUE THREAD

**Issue by jorisslob** [Siriah/codegarden#4]
I think the package.json is missing a dependency on tslint.
Or the README needs updating that gulp test requires the installation of tslint.

```
~/Repos/codegarden$ gulp test
module.js:328
    throw err;
    ^

Error: Cannot find module 'tslint'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/arabis5/Repos/codegarden/node_modules/gulp-tslint/index.js:5:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

```

and after running a

```
npm install tslint
```

I get the following errors:

```
~/Repos/codegarden$ gulp test
[20:41:56] Using gulpfile ~/Repos/codegarden/gulpfile.js
[20:41:56] Starting 'test'...
[20:41:56] Starting 'clean'...
[20:41:56] Finished 'clean' after 93 ms
[20:41:56] Starting 'copy'...
[20:41:56] Finished 'copy' after 177 ms
[20:41:56] Starting 'assets'...
[20:41:56] Finished 'assets' after 57 ms
[20:41:56] Starting 'scripts'...
[20:41:58] Finished 'scripts' after 2.03 s
[20:41:58] Starting 'ts-test'...
[20:42:00] Finished 'ts-test' after 2.21 s
[20:42:00] Starting 'jasmine-karma'...
[20:42:00] Finished 'jasmine-karma' after 3.74 ms
[20:42:00] Finished 'test' after 4.58 s
22 10 2016 20:42:00.973:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
22 10 2016 20:42:01.001:INFO [launcher]: Starting browser PhantomJS
22 10 2016 20:42:01.007:ERROR [launcher]: No binary for PhantomJS browser on your platform.
  Please, set "PHANTOMJS_BIN" env variable.
22 10 2016 20:42:01.008:ERROR [launcher]: [TypeError: Cannot read property 'stderr' of undefined]
TypeError: Cannot read property 'stderr' of undefined
    at Object._start (/home/arabis5/Repos/codegarden/node_modules/karma-phantomjs-launcher/index.js:79:18)
    at Object.<anonymous> (/home/arabis5/Repos/codegarden/node_modules/karma/lib/launchers/process.js:14:10)
    at emitOne (events.js:82:20)
    at Object.emit (events.js:169:7)
    at Object.start (/home/arabis5/Repos/codegarden/node_modules/karma/lib/launchers/base.js:42:10)
    at /home/arabis5/Repos/codegarden/node_modules/karma/lib/launcher.js:94:17
    at next (/home/arabis5/Repos/codegarden/node_modules/batch/index.js:118:7)
    at Batch.end (/home/arabis5/Repos/codegarden/node_modules/batch/index.js:154:5)
    at launch (/home/arabis5/Repos/codegarden/node_modules/karma/lib/launcher.js:111:11)
    at invoke (/home/arabis5/Repos/codegarden/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/home/arabis5/Repos/codegarden/node_modules/karma/lib/server.js:171:24)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1263:10)
    at nextTickCallbackWith1Arg (node.js:430:9)

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Failed Unit Tests!
```

So there are multiple requirements missing in the documentation or installer.

**Comment by Siriah** [comment]
The dependency on tslint was indeed missing, but this was only a problem when using npm 3+: when using npm 2, it was automatically installed as a peer dependency.

I've added the missing dependency on tslint, upgraded all dependencies to the newest version and upgraded my local npm to version 3.10.9 to confirm that a fresh install works on my machine now. Not sure about the missing 'binary for PhantomJS' and if this is a problem that will still occur for anyone now.

**Comment by jorisslob** [comment]
The problem still occurred on my new Ubuntu installation, but I found the problem:

http://stackoverflow.com/questions/28336214/no-binary-for-phantomjs-browser-on-your-platform-please-set-phantomjs-bin-en

Phantomjs was located somewhere else in my ubuntu installation I had to change the export line to this:

`export PHANTOMJS_BIN=/usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom`
